# buildspec-install.yml
version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - echo "Installing system dependencies..."
      - yum update -y
      - yum install -y python3-devel gcc xmlsec1-devel xmlsec1-openssl-devel libtool-ltdl-devel
      
      - echo "Installing Python dependencies..."
      - pip install --upgrade pip
      - pip install pytest flask requests
      - pip install gevent==22.10.2
      - pip install 'urllib3<1.27,>=1.25.4'
      - pip install boto3==1.34.147 botocore==1.34.147
      - pip install xmlsec==1.3.13
      - grep -v -E "gevent|urllib3|boto3|botocore|xmlsec" requirements.txt > filtered_requirements.txt
      - pip install -r filtered_requirements.txt

artifacts:
  files:
    - '**/*'
  base-directory: '.'

cache:
  paths:
    - '/root/.cache/pip'
