version: 0.2

phases:
  build:
    commands:
      - echo "Running security checks..."
      - pip install safety bandit
      - safety check
      - bandit -r ./ -f json -o security-report.json || echo "Security scan complete with findings"
      
artifacts:
  files:
    - '**/*'
    - security-report.json
  base-directory: '.'
