# buildspec-security.yml
version: 0.2

env:
  variables:
    PYTHONPATH: '/usr/local/lib/python3.9/site-packages'

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - pip install --upgrade pip
      - pip install --upgrade setuptools wheel

  pre_build:
    commands:
      - echo "Installing security tools..."
      - pip install safety bandit werkzeug>=3.0.6

  build:
    commands:
      - echo "Running security checks..."
      - safety scan --output json || true
      - bandit -r ./ -f json -o security-report.json || true
      - echo "Running dependency check..."
      - pip freeze > dependencies.txt
      - safety check -r dependencies.txt --full-report --output json > safety-report.json || true
      
reports:
  security_report:
    files:
      - security-report.json
      - safety-report.json
    file-format: JSON

artifacts:
  files:
    - security-report.json
    - safety-report.json
    - dependencies.txt
  discard-paths: yes
