version: 0.2

phases:
  pre_build:
    commands:
      - echo "Installing test dependencies..."
      - pip install pytest pytest-cov
      - pip install gevent==22.10.2  # Necessário para os testes
      
  build:
    commands:
      - echo "Running tests..."
      - python -m pytest tests/  # Removido o --cov=./ --cov-report=xml

artifacts:
  files:
    - '**/*'
  base-directory: '.'
