version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
  
  pre_build:
    commands:
      - echo "Starting build phase..."
      
  build:
    commands:
      - echo "Creating deployment package..."
      - mkdir -p build/
      - cp -r * build/ || true
      - cd build
      - zip -r ../deployment.zip ./*
      - cd ..
      - ls -la  # Verificar os arquivos gerados
      - echo "Deployment package contents:"
      - unzip -l deployment.zip

artifacts:
  files:
    - deployment.zip
    - appspec.yml
    - scripts/**/*
    - requirements.txt
  base-directory: '.'
  discard-paths: no

cache:
  paths:
    - '/root/.cache/pip/**/*'