version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.10    # Removendo o .0 para usar a versão principal
    commands:
      - python --version
      - pip install --upgrade pip
      - pip install virtualenv

  pre_build:
    commands:
      - virtualenv venv
      - . venv/bin/activate
      - pip install -r requirements.txt

  build:
    commands:
      - echo Build started on `date`
      - python -m pytest tests/ || echo "No tests found or tests failed"

  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - '**/*'
  base-directory: .

cache:
  paths:
    - '/root/.cache/pip'
    - 'venv/**/*'
