version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.10
    commands:
      - echo "Installing system dependencies..."
      - yum update -y
      - yum install -y python3-devel gcc
      - yum install -y xmlsec1-devel xmlsec1-openssl-devel libtool-ltdl-devel
      - yum install -y openssl-devel libxml2-devel xmlsec1 xmlsec1-openssl
      - yum install -y python3-pip
      
  pre_build:
    commands:
      - echo "Setting up virtual environment..."
      - python -m venv venv
      - . venv/bin/activate
      - echo "Upgrading pip and setuptools..."
      - pip install --upgrade pip==24.1.2
      - pip install setuptools==68.0.0
      - echo "Installing base dependencies first..."
      - pip install wheel
      - pip install "gevent==22.10.2"  # Instalando gevent primeiro para evitar conflitos
      - echo "Installing test dependencies..."
      - pip install pytest pytest-cov pytest-env pytest-gevent pytest-lazy-fixture pytest-mock
      - echo "Installing application dependencies..."
      - pip install -r requirements.txt || {
          echo "Retrying installation without dependencies that might be causing issues...";
          pip install -r <(grep -v "gevent" requirements.txt);
        }
      
  build:
    commands:
      - echo "Running tests..."
      - . venv/bin/activate
      - python -m pytest tests/

artifacts:
  files:
    - '**/*'
    - appspec.yml
    - scripts/**/*
  base-directory: '.'

cache:
  paths:
    - venv/**/*
    - /root/.cache/pip
