AWSTemplateFormatVersion: '2010-09-09'
Description: 'IAM roles for CodeBuild Security Checks'

Resources:
  CodeBuildSecurityRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${AWS::StackName}-SecurityCheckRole'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: codebuild.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: CodeBuildSecurityPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              # Logs
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource:
                  - !Sub 'arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/codebuild/*'
                  - !Sub 'arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/codebuild/*:*'
              
              # S3 Pipeline Artifacts - Específico para o bucket do pipeline
              - Effect: Allow
                Action:
                  - s3:GetObject*
                  - s3:PutObject*
                  - s3:List*
                Resource:
                  - 'arn:aws:s3:::cicdstack-pipelineartifactsbucket-*'
                  - 'arn:aws:s3:::cicdstack-pipelineartifactsbucket-*/*'
              
              # S3 Generic - Para outros buckets necessários
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                  - s3:GetObjectVersion
                  - s3:ListBucket
                Resource: 
                  - !Sub 'arn:aws:s3:::${AWS::AccountId}-${AWS::Region}-pipeline-artifacts/*'
                  - !Sub 'arn:aws:s3:::${AWS::AccountId}-${AWS::Region}-pipeline-artifacts'
              
              # CodeBuild Reports
              - Effect: Allow
                Action:
                  - codebuild:CreateReportGroup
                  - codebuild:CreateReport
                  - codebuild:UpdateReport
                  - codebuild:BatchPutTestCases
                  - codebuild:BatchPutCodeCoverages
                  - codebuild:UpdateReportGroup
                Resource:
                  - !Sub 'arn:aws:codebuild:${AWS::Region}:${AWS::AccountId}:report-group/*'
                  - !Sub 'arn:aws:codebuild:${AWS::Region}:${AWS::AccountId}:report-group/CICDStack-Security-*'
              
              # CodeBuild General
              - Effect: Allow
                Action:
                  - codebuild:StartBuild
                  - codebuild:BatchGetBuilds
                  - codebuild:StopBuild
                Resource:
                  - !Sub 'arn:aws:codebuild:${AWS::Region}:${AWS::AccountId}:project/*'

Outputs:
  CodeBuildRoleArn:
    Description: ARN of the CodeBuild Role for Security Checks
    Value: !GetAtt CodeBuildSecurityRole.Arn
    Export:
      Name: !Sub '${AWS::StackName}-SecurityCheckRoleArn'