version: 0.0
os: linux
files:
  - source: /app
    destination: /opt/confidant

permissions:
  - object: /opt/confidant
    pattern: "**"
    owner: ec2-user
    group: ec2-user
    mode: 755
    type:
      - file
      - directory

hooks:
  BeforeInstall:
    - location: infrastructure/scripts/before_install.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: infrastructure/scripts/after_install.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: infrastructure/scripts/start_application.sh
      timeout: 300
      runas: root
  ValidateService:
    - location: infrastructure/scripts/validate_service.sh
      timeout: 300
      runas: root