version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
  pre_build:
    commands:
      - echo Starting build phase
  build:
    commands:
      - mkdir -p deployment
      - cp -r app/* deployment/
      - mkdir -p deployment/scripts
      - cp infrastructure/scripts/* deployment/scripts/
      - cp infrastructure/pipeline/appspec.yml deployment/
      - ls -la deployment/
      - cd deployment
      - zip -r ../deployment.zip .
      - cd ..
      - unzip -l deployment.zip

artifacts:
  files:
    - deployment.zip
  discard-paths: no