version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
  build:
    commands:
      - echo "Creating deployment package..."
      # Criar estrutura temporária para app e scripts
      - mkdir -p confidant
      - mkdir -p confidant/app
      - mkdir -p confidant/scripts
      
      # Copiar arquivos da aplicação
      - cp -r app/* confidant/app/
      - cp -r infrastructure/scripts/* confidant/scripts/
      
      # Copiar appspec.yml FORA da pasta build
      - cp infrastructure/pipeline/appspec.yml appspec.yml
      
      # Criar o zip com o conteúdo de build primeiro
      - cd confidant
      - zip -r ../deployment-archive.zip .
      - cd ..
      
      # Adicionar appspec.yml na raiz do zip
      - zip -g deployment-archive.zip appspec.yml
      
      # Verificar o conteúdo do zip
      - echo "Deployment archive contents:"
      - unzip -l deployment-archive.zip
      
artifacts:
  files:
    - deployment-archive.zip
  discard-paths: no
