version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
  build:
    commands:
      - echo "Creating deployment package..."
      # Criar estrutura correta
      - cp infrastructure/pipeline/appspec.yml ./appspec.yml
      - mkdir -p temp/app
      - mkdir -p temp/scripts
      # Copiar arquivos mantendo estrutura
      - cp -r app/* temp/app/
      - cp -r infrastructure/scripts/* temp/scripts/
      # Criar o zip com a estrutura correta
      - cd temp
      - zip -r ../deployment-archive.zip .
      - cd ..
      - zip -g deployment-archive.zip appspec.yml
      # Verificar conteúdo
      - unzip -l deployment-archive.zip
      - echo "Deployment package created"

artifacts:
  files:
    - deployment-archive.zip
  base-directory: '.'