version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - echo "Installing dependencies..."
      - pip install --upgrade pip
      - pip install -r app/requirements.txt
      
artifacts:
  files:
    - app/**/*
    - infrastructure/**/*
  base-directory: '.'