version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
  
  build:
    commands:
      - echo "Preparing deployment package..."
      
      # Create a clean working directory
      - rm -rf deployment deployment.zip
      
      # First, copy appspec.yml to the current directory
      - cp infrastructure/pipeline/appspec.yml ./appspec.yml
      
      # Create the application structure
      - mkdir -p app
      - mkdir -p scripts
      
      # Copy files maintaining the structure specified in appspec.yml
      - cp -r app/* app/
      - cp infrastructure/scripts/*.sh scripts/
      - chmod +x scripts/*.sh
      
      # Create the deployment package
      - zip -r deployment.zip appspec.yml app/ scripts/
      
      # Verify the package structure
      - echo "Verifying deployment package contents:"
      - unzip -l deployment.zip
      - echo "Checking appspec.yml location:"
      - unzip -t deployment.zip appspec.yml

artifacts:
  files:
    - deployment.zip
  discard-paths: no