version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
  build:
    commands:
      - echo "Creating deployment package..."
      - mkdir -p build
      - cp -r app/* build/
      - cp infrastructure/scripts/* build/
      - cp infrastructure/pipeline/appspec.yml build/appspec.yml
      - cd build
      - ls -la
      - zip -r deployment-archive.zip .
      - cd ..
      - mv build/deployment-archive.zip .
      - ls -la

artifacts:
  files:
    - deployment-archive.zip
  base-directory: '.'