version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
  
  build:
    commands:
      - echo "Creating deployment package..."
      
      # Limpar qualquer arquivo temporário anterior
      - rm -rf deployment_temp deployment.zip
      
      # Criar diretórios temporários
      - mkdir -p deployment_temp/app
      - mkdir -p deployment_temp/scripts
      
      # Copiar os arquivos para a estrutura temporária
      - cp -r app/* deployment_temp/app/
      - cp infrastructure/scripts/*.sh deployment_temp/scripts/
      - cp infrastructure/pipeline/appspec.yml deployment_temp/
      
      # IMPORTANTE: Entrar no diretório temporário para criar o zip
      - cd deployment_temp
      
      # Criar o zip A PARTIR DESTE DIRETÓRIO
      # Isso faz com que os arquivos fiquem na raiz do zip
      - zip -r ../deployment.zip .
      
      # Voltar ao diretório original
      - cd ..
      
      # Verificar a estrutura do zip
      - echo "Verification of zip contents:"
      - unzip -l deployment.zip

artifacts:
  files:
    - deployment.zip
  discard-paths: no