version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
  
  build:
    commands:
      - echo "Creating deployment package..."
      
      # Criar diretório temporário completamente limpo
      - rm -rf deployment_temp
      - mkdir deployment_temp
      
      # IMPORTANTE: Primeiro copiamos o appspec.yml para a raiz
      - cp infrastructure/pipeline/appspec.yml appspec.yml
      
      # Criar estrutura de diretórios para os arquivos da aplicação
      - mkdir -p deployment_temp/app
      - mkdir -p deployment_temp/scripts
      
      # Copiar arquivos da aplicação
      - cp -r app/* deployment_temp/app/
      
      # Copiar scripts
      - cp infrastructure/scripts/*.sh deployment_temp/scripts/
      - chmod +x deployment_temp/scripts/*.sh
      
      # Criar o zip incluindo o appspec.yml na raiz
      - zip -r deployment.zip appspec.yml deployment_temp/*
      
      # Verificar a estrutura do zip - crucial para debug
      - echo "Verifying zip contents:"
      - unzip -l deployment.zip
      - echo "appspec.yml should be at root level:"
      - unzip -l deployment.zip | grep appspec.yml

artifacts:
  files:
    - deployment.zip
  discard-paths: no