version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
  
  build:
    commands:
      - echo "Creating deployment package with correct directory structure..."
      
      # Criar estrutura de diretórios limpa
      - mkdir -p deployment/app
      - mkdir -p deployment/scripts
      
      # Copiar arquivos da aplicação para dentro da pasta app/
      - cp app.py deployment/app/
      - cp requirements.txt deployment/app/
      
      # Se existir a pasta config, copiá-la também
      - if [ -d "config" ]; then cp -r config deployment/app/; fi
      
      # Copiar scripts de deployment
      - cp infrastructure/scripts/* deployment/scripts/
      
      # Copiar appspec.yml ajustado para a raiz
      - cp infrastructure/pipeline/appspec.yml deployment/
      
      # Criar o pacote de deployment
      - cd deployment
      - zip -r ../deployment.zip .
      - cd ..
      
      # Verificar conteúdo para garantir estrutura correta
      - echo "Verificando conteúdo do arquivo de deployment:"
      - unzip -l deployment.zip

artifacts:
  files:
    - deployment.zip
  discard-paths: no
