version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
  
  build:
    commands:
      - echo "Creating deployment package..."
      
      # Criar estrutura limpa
      - rm -rf deployment deployment.zip
      - mkdir -p deployment
      
      # Copiar arquivos para a estrutura correta
      - cp -r app deployment/
      - mkdir -p deployment/scripts
      - cp infrastructure/scripts/*.sh deployment/scripts/
      - cp infrastructure/pipeline/appspec.yml deployment/appspec.yml
      
      # Criar o zip a partir do diretório correto
      - cd deployment
      - zip -r ../deployment.zip .
      - cd ..
      
      # Verificação crítica
      - echo "Verificando estrutura do deployment:"
      - unzip -l deployment.zip
      - echo "Verificando localização do appspec.yml:"
      - unzip -l deployment.zip | grep appspec.yml

artifacts:
  files:
    - deployment.zip
  discard-paths: no