version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
  
  pre_build:
    commands:
      - echo "Starting build phase..."
      
  build:
    commands:
      - echo "Creating deployment package..."
      - mkdir -p build/
      - mkdir -p build/app
      - mkdir -p build/opt/confidant/scripts
      - cp -r app/* build/app/
      - cp -r infrastructure/scripts/* build/opt/confidant/scripts/
      - cp infrastructure/pipeline/appspec.yml build/
      - cd build
      - zip -r ../deployment.zip ./*
      - cd ..
      - echo "Deployment package contents:"
      - unzip -l deployment.zip

artifacts:
  files:
    - deployment.zip
    - infrastructure/pipeline/appspec.yml
  base-directory: '.'
  discard-paths: no