version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
  
  pre_build:
    commands:
      - echo "Starting build phase..."
      
  build:
    commands:
      - echo "Creating deployment package..."
      - mkdir -p build/
      - cp -r app/* build/
      - cp -r infrastructure/scripts build/scripts
      - cd build
      - zip -r ../deployment.zip ./*
      - cd ..
      - echo "Deployment package contents:"
      - unzip -l deployment.zip

artifacts:
  files:
    - deployment.zip
    - infrastructure/pipeline/appspec.yml
    - infrastructure/scripts/**/*
    - app/**/*
  base-directory: '.'
  discard-paths: no

cache:
  paths:
    - '/root/.cache/pip/**/*'