version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
  
  build:
    commands:
      - echo "Preparing deployment package..."
      
      # Create a clean working directory for our deployment
      - rm -rf deployment-package
      - mkdir -p deployment-package
      
      # First, copy appspec.yml to our deployment package root
      - cp infrastructure/pipeline/appspec.yml deployment-package/
      
      # Create the directory structure in our package
      - mkdir -p deployment-package/app
      - mkdir -p deployment-package/scripts
      
      # Copy application files - note how we're copying FROM app TO deployment-package/app
      - cp -r app/* deployment-package/app/
      
      # Copy deployment scripts
      - cp infrastructure/scripts/*.sh deployment-package/scripts/
      - chmod +x deployment-package/scripts/*.sh
      
      # Create the deployment package from our prepared directory
      - cd deployment-package
      - zip -r ../deployment.zip .
      - cd ..
      
      # Verify the package contents
      - echo "Verifying deployment package structure:"
      - unzip -l deployment.zip

artifacts:
  files:
    - deployment.zip
  discard-paths: no