version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
  
  build:
    commands:
      - echo "Creating deployment package..."
      - mkdir -p build
      
      # Copiar arquivos da aplicação
      - cp -r app/* build/
      
      # Copiar scripts de deployment
      - mkdir -p build/scripts
      - cp infrastructure/scripts/* build/scripts/
      
      # Copiar appspec.yml para a raiz
      - cp infrastructure/pipeline/appspec.yml appspec.yml
      
      # Criar o pacote de deployment
      - cd build
      - zip -r ../deployment.zip .
      - cd ..
      - zip -g deployment.zip appspec.yml
      
      # Verificar conteúdo
      - echo "Deployment archive contents:"
      - unzip -l deployment.zip

artifacts:
  files:
    - deployment.zip
  discard-paths: no
